const { parseISO, format } = require("date-fns");
const { pools } = require("../../config/mysqldbconfig");
const { executeTmc } = require("../../config/oracleExecutor");
const { getTmcConnection, oracledb } = require("../../config/oradbconfig");
module.exports = {
  getSupplierList: async (data) => {
    const sql = `SELECT
                           SU_CODE,SUC_NAME,SUC_ALIAS,SUC_STATUS,SUC_PERSON,SUC_ADD1,SUC_ADD2,SUC_ADD3,SUC_ADD4,SUC_PHONE,
                           SUC_FAX,SUC_MOBILE,SUC_CSTNO,SUC_KGSTNO,SUC_TAXDATE,SUC_DLNO1,SUC_DLNO2,SUC_DLNO3,SUC_DLNO4,
                           SUD_DLDATE,SUN_CRDPERIOD,SUN_CRDLIMIT,SUN_OUTSTANDING,SUN_LEADTIME,SUN_SUPPLY,SUC_EMAIL,SUN_RANK,
                           SUN_RANK,US_CODE,SUC_TYPE,SUC_WEBSITE,AC_CODE,GAC_CODE,SUN_ORDER,SUD_EDDATE,SUC_OLDCODE,SUC_TIN,
                           NACC_CODE,SUC_CURRENCY,SUC_DELIVERY,VENDOR_CODE,SUC_PERSON1,SUC_PERSON2,SUC_PERSON3,SUC_PERSON_MOB1,
                           SUC_PERSON_MOB2,SUC_PERSON_MOB3,SUC_MFCODE,SUC_GSTIN,SUC_IGST,SUC_STCODE,SUC_TERMS,SUC_GROUPSUPPLIER,
                           SUC_PANNO
                     FROM
                           SUPPLIER
                     WHERE
                           SUC_STATUS='Y' AND SUC_NAME LIKE:supname`;
    try {
      const result = await executeTmc(
        sql,
        {
          supname: "%" + data.SUC_NAME + "%",
        },
        { outFormat: oracledb.OUT_FORMAT_OBJECT },
      );
      return result.rows;
    } catch (error) {
      console.log(error);
      throw error;
    }
  },
  getActiveSupplierList: async () => {
    const sql = `SELECT
                           SUPPLIER.SU_CODE,SUC_NAME,SUC_ALIAS,SUC_STATUS
                     FROM
                           SUPPLIER
                        LEFT JOIN PORDMAST ON PORDMAST.SU_CODE=SUPPLIER.SU_CODE
                     WHERE
                           SUC_STATUS='Y' AND PORDMAST.ST_CODE IN ('C001','C002','C003','C004','0037')
                           AND PORDMAST.POC_CANCEL IS NULL AND PORDMAST.POC_CLOSE IS NULL
                           AND PORDMAST.POD_DATE >= ADD_MONTHS(SYSDATE, -12)
                           AND PORDMAST.PON_TOTAPPROVALSCOMP=3
                     GROUP BY  SUPPLIER.SU_CODE,SUC_NAME,SUC_ALIAS,SUC_STATUS
                     ORDER BY SUC_NAME`;
    try {
      const result = await executeTmc(sql, {}, { outFormat: oracledb.OUT_FORMAT_OBJECT });
      // callBack(null, result.rows);
      return result.rows;
    } catch (error) {
      console.log(error);
      throw error;
    }
  },


  getCommonReport: async (data) => {
    const from = data.census_datefrom ? parseISO(data.census_datefrom) : null;
    const to = data.census_dateto ? parseISO(data.census_dateto) : null;

    // Format to Oracle format
    const FROM_DATE = from ? format(from, "dd/MM/yyyy HH:mm:ss") : null;
    const TO_DATE = to ? format(to, "dd/MM/yyyy HH:mm:ss") : null;

    const sql = `
             SELECT ROW_NUMBER() OVER (ORDER BY I.DMD_DATE) AS "SLNO", 
            I.IPD_DATE AS"ADMISSION_DATE", 
            ROUND(I.IPD_DISC - I.IPD_DATE) AS"DURATION_OF_STAY", 
            I.PT_NO AS"PATIENT_NO", 
            I.IP_NO AS "ADMISS_NO",
            AD.RSC_DESC AS "ADMISS_REASON",
            DECODE(I.IPC_STATUS,'R','RECOVERED','E','EXPIRED','Q','DAMA','U','UNCHANGED','D','DIAGNOSIS','A','ABSCONDED','T','AUTOPSY','H','TRANSFER','O','OTHERS','M','DAMA')"DISCHARGE_STATUS",
            I.PTC_PTNAME AS"PATIENT_NAME", 
            D.DOC_NAME AS"DOCTOR_NAME",
            DP.DPC_DESC AS"DEPARTMENT_NAME", 
            N.NSC_DESC AS"NURSTATION_NAME", 
            B.BDC_NO AS"BED_NO", 
            TO_CHAR(I.IPD_DATE,'DD/MM/YYYY HH24:MI:SS') AS"ADMIS_DATE_TIME", 
            DECODE(I.PTC_TYPE,'R','CREDIT','C','CASH') AS"BILL_TYPES", 
            TO_CHAR(DD.REQ_DATE,'DD/MM/YYYY HH24:MI:SS') AS"DIS_ANNOUNCED", 
            TO_CHAR(LATEST_MRETREQMAST.MRD_DATE,'DD/MM/YYYY HH24:MI:SS') AS"MED_RET_REQ_DATE", 
            TO_CHAR(LATEST_MRETMAST.MRD_RETDATE,'DD/MM/YYYY HH24:MI:SS') AS"RET_BILL_TIME", 
            TO_CHAR(DS.APRVD_DATE,'DD/MM/YYYY HH24:MI:SS') AS"DIS_SUM_APR_DATE", 
            TO_CHAR(LATEST_PATDRGREQMST.DRD_DATE,'DD/MM/YYYY HH24:MI:SS') AS"MED_REQUEST_TIME", 
            TO_CHAR(LATEST_PATDRGREQMST.DRD_ISSUEDATE,'DD/MM/YYYY HH24:MI:SS') AS"MED_ISSUE_TIME", 
            TO_CHAR(LATEST_PBILLMAST.BMD_DISPENSETIME,'DD/MM/YYYY HH24:MI:SS') AS"MED_DISPENSE_TIME", 
            TO_CHAR(LATEST_PATDRGREQMST.DRD_ACCEPTDATE,'DD/MM/YYYY HH24:MI:SS') AS"MED_ACCEPT_TIME",
            TO_CHAR(I.IPD_DISC,'DD/MM/YYYY HH24:MI:SS') AS"DISCHARGE_DATE", 
            TO_CHAR(I.DMD_DATE,'DD/MM/YYYY HH24:MI:SS') AS"BILL_DATE", 
            TO_CHAR(LATEST_RECEIPT.IRD_DATE,'DD/MM/YYYY HH24:MI:SS') AS"RECEIPT_DATE", 
            TO_CHAR(I.IPD_ACTRELEASE,'DD/MM/YYYY HH24:MI:SS') AS"PATIENT_OUT",
            TO_CHAR(DD.CANCEL_DATE ,'DD/MM/YYYY HH24:MI:SS') AS"DIS_REQ_CANCEL",
EXTRACT(DAY FROM NUMTODSINTERVAL(LATEST_MRETREQMAST.MRD_DATE - DD.REQ_DATE, 'DAY')) * 24 +
        EXTRACT(HOUR FROM NUMTODSINTERVAL(LATEST_MRETREQMAST.MRD_DATE - DD.REQ_DATE, 'DAY')) || ':' ||
        LPAD(EXTRACT(MINUTE FROM NUMTODSINTERVAL(LATEST_MRETREQMAST.MRD_DATE - DD.REQ_DATE, 'DAY')), 2, '0') || ':' ||
        LPAD(TRUNC(EXTRACT(SECOND FROM NUMTODSINTERVAL(LATEST_MRETREQMAST.MRD_DATE - DD.REQ_DATE, 'DAY'))), 2, '0') AS "TAT_ANSMT_MEDRET_REQ",
    EXTRACT(DAY FROM NUMTODSINTERVAL(LATEST_MRETMAST.MRD_RETDATE - LATEST_MRETREQMAST.MRD_DATE, 'DAY')) * 24 +
        EXTRACT(HOUR FROM NUMTODSINTERVAL(LATEST_MRETMAST.MRD_RETDATE - LATEST_MRETREQMAST.MRD_DATE, 'DAY')) || ':' ||
        LPAD(EXTRACT(MINUTE FROM NUMTODSINTERVAL(LATEST_MRETMAST.MRD_RETDATE - LATEST_MRETREQMAST.MRD_DATE, 'DAY')), 2, '0') || ':' ||
        LPAD(TRUNC(EXTRACT(SECOND FROM NUMTODSINTERVAL(LATEST_MRETMAST.MRD_RETDATE - LATEST_MRETREQMAST.MRD_DATE, 'DAY'))), 2, '0') AS "TAT_MEDRETREQ_RETBILL",
    EXTRACT(DAY FROM NUMTODSINTERVAL(DS.APRVD_DATE - DD.REQ_DATE, 'DAY')) * 24 +
        EXTRACT(HOUR FROM NUMTODSINTERVAL(DS.APRVD_DATE - DD.REQ_DATE, 'DAY')) || ':' ||
        LPAD(EXTRACT(MINUTE FROM NUMTODSINTERVAL(DS.APRVD_DATE - DD.REQ_DATE, 'DAY')), 2, '0') || ':' ||
        LPAD(TRUNC(EXTRACT(SECOND FROM NUMTODSINTERVAL(DS.APRVD_DATE - DD.REQ_DATE, 'DAY'))), 2, '0') AS "TAT_ANSMT_DISSUM",   
    EXTRACT(DAY FROM NUMTODSINTERVAL(LATEST_PATDRGREQMST.DRD_DATE - DS.APRVD_DATE, 'DAY')) * 24 +
        EXTRACT(HOUR FROM NUMTODSINTERVAL(LATEST_PATDRGREQMST.DRD_DATE - DS.APRVD_DATE, 'DAY')) || ':' ||
        LPAD(EXTRACT(MINUTE FROM NUMTODSINTERVAL(LATEST_PATDRGREQMST.DRD_DATE - DS.APRVD_DATE, 'DAY')), 2, '0') || ':' ||
        LPAD(TRUNC(EXTRACT(SECOND FROM NUMTODSINTERVAL(LATEST_PATDRGREQMST.DRD_DATE - DS.APRVD_DATE, 'DAY'))), 2, '0') AS "TAT_DISSUM_ADV_REQ",
    EXTRACT(DAY FROM NUMTODSINTERVAL(LATEST_PATDRGREQMST.DRD_ISSUEDATE - LATEST_PATDRGREQMST.DRD_DATE, 'DAY')) * 24 +
        EXTRACT(HOUR FROM NUMTODSINTERVAL(LATEST_PATDRGREQMST.DRD_ISSUEDATE - LATEST_PATDRGREQMST.DRD_DATE, 'DAY')) || ':' ||
        LPAD(EXTRACT(MINUTE FROM NUMTODSINTERVAL(LATEST_PATDRGREQMST.DRD_ISSUEDATE - LATEST_PATDRGREQMST.DRD_DATE, 'DAY')), 2, '0') || ':' ||
        LPAD(TRUNC(EXTRACT(SECOND FROM NUMTODSINTERVAL(LATEST_PATDRGREQMST.DRD_ISSUEDATE - LATEST_PATDRGREQMST.DRD_DATE, 'DAY'))), 2, '0') AS "TAT_ADV_REQ_ADVBILL",                 
    EXTRACT(DAY FROM NUMTODSINTERVAL(LATEST_PBILLMAST.BMD_DISPENSETIME - LATEST_PATDRGREQMST.DRD_ISSUEDATE, 'DAY')) * 24 +
        EXTRACT(HOUR FROM NUMTODSINTERVAL(LATEST_PBILLMAST.BMD_DISPENSETIME - LATEST_PATDRGREQMST.DRD_ISSUEDATE, 'DAY')) || ':' ||
        LPAD(EXTRACT(MINUTE FROM NUMTODSINTERVAL(LATEST_PBILLMAST.BMD_DISPENSETIME - LATEST_PATDRGREQMST.DRD_ISSUEDATE, 'DAY')), 2, '0') || ':' ||
        LPAD(TRUNC(EXTRACT(SECOND FROM NUMTODSINTERVAL(LATEST_PBILLMAST.BMD_DISPENSETIME - LATEST_PATDRGREQMST.DRD_ISSUEDATE, 'DAY'))), 2, '0') AS "TAT_ADVBILL_DISPENSE",    
    EXTRACT(DAY FROM NUMTODSINTERVAL(LATEST_PATDRGREQMST.DRD_ACCEPTDATE - LATEST_PBILLMAST.BMD_DISPENSETIME, 'DAY')) * 24 +
        EXTRACT(HOUR FROM NUMTODSINTERVAL(LATEST_PATDRGREQMST.DRD_ACCEPTDATE - LATEST_PBILLMAST.BMD_DISPENSETIME, 'DAY')) || ':' ||
        LPAD(EXTRACT(MINUTE FROM NUMTODSINTERVAL(LATEST_PATDRGREQMST.DRD_ACCEPTDATE - LATEST_PBILLMAST.BMD_DISPENSETIME, 'DAY')), 2, '0') || ':' ||
        LPAD(TRUNC(EXTRACT(SECOND FROM NUMTODSINTERVAL(LATEST_PATDRGREQMST.DRD_ACCEPTDATE - LATEST_PBILLMAST.BMD_DISPENSETIME, 'DAY'))), 2, '0') AS "TAT_DISPENSE_ACCEPT",            
    EXTRACT(DAY FROM NUMTODSINTERVAL(I.IPD_DISC - DD.REQ_DATE, 'DAY')) * 24 +
        EXTRACT(HOUR FROM NUMTODSINTERVAL(I.IPD_DISC - DD.REQ_DATE, 'DAY')) || ':' ||
        LPAD(EXTRACT(MINUTE FROM NUMTODSINTERVAL(I.IPD_DISC - DD.REQ_DATE, 'DAY')), 2, '0') || ':' ||
        LPAD(TRUNC(EXTRACT(SECOND FROM NUMTODSINTERVAL(I.IPD_DISC - DD.REQ_DATE, 'DAY'))), 2, '0') AS "TAT_ANOUN_DISENTRY",    
    EXTRACT(DAY FROM NUMTODSINTERVAL(I.DMD_DATE - I.IPD_DISC, 'DAY')) * 24 +
        EXTRACT(HOUR FROM NUMTODSINTERVAL(I.DMD_DATE - I.IPD_DISC, 'DAY')) || ':' ||
        LPAD(EXTRACT(MINUTE FROM NUMTODSINTERVAL(I.DMD_DATE - I.IPD_DISC, 'DAY')), 2, '0') || ':' ||
        LPAD(TRUNC(EXTRACT(SECOND FROM NUMTODSINTERVAL(I.DMD_DATE - I.IPD_DISC, 'DAY'))), 2, '0') AS "TAT_DISENTRY_DISBILL",     
    EXTRACT(DAY FROM NUMTODSINTERVAL(LATEST_RECEIPT.IRD_DATE - I.DMD_DATE, 'DAY')) * 24 +
        EXTRACT(HOUR FROM NUMTODSINTERVAL(LATEST_RECEIPT.IRD_DATE - I.DMD_DATE, 'DAY')) || ':' ||
        LPAD(EXTRACT(MINUTE FROM NUMTODSINTERVAL(LATEST_RECEIPT.IRD_DATE - I.DMD_DATE, 'DAY')), 2, '0') || ':' ||
        LPAD(TRUNC(EXTRACT(SECOND FROM NUMTODSINTERVAL(LATEST_RECEIPT.IRD_DATE - I.DMD_DATE, 'DAY'))), 2, '0') AS "TAT_DISBILL_RECEIPT",     
    EXTRACT(DAY FROM NUMTODSINTERVAL(I.IPD_ACTRELEASE - LATEST_RECEIPT.IRD_DATE, 'DAY')) * 24 +
        EXTRACT(HOUR FROM NUMTODSINTERVAL(I.IPD_ACTRELEASE - LATEST_RECEIPT.IRD_DATE, 'DAY')) || ':' ||
        LPAD(EXTRACT(MINUTE FROM NUMTODSINTERVAL(I.IPD_ACTRELEASE - LATEST_RECEIPT.IRD_DATE, 'DAY')), 2, '0') || ':' ||
        LPAD(TRUNC(EXTRACT(SECOND FROM NUMTODSINTERVAL(I.IPD_ACTRELEASE - LATEST_RECEIPT.IRD_DATE, 'DAY'))), 2, '0') AS "TAT_RECEIPT_PTOUT",      
    EXTRACT(DAY FROM NUMTODSINTERVAL(I.IPD_ACTRELEASE - DD.REQ_DATE, 'DAY')) * 24 +
        EXTRACT(HOUR FROM NUMTODSINTERVAL(I.IPD_ACTRELEASE - DD.REQ_DATE, 'DAY')) || ':' ||
        LPAD(EXTRACT(MINUTE FROM NUMTODSINTERVAL(I.IPD_ACTRELEASE - DD.REQ_DATE, 'DAY')), 2, '0') || ':' ||
        LPAD(TRUNC(EXTRACT(SECOND FROM NUMTODSINTERVAL(I.IPD_ACTRELEASE - DD.REQ_DATE, 'DAY'))), 2, '0') AS "TAT_ANSMT_PTOUT"  
 FROM IPADMISS I
    LEFT JOIN (
        SELECT DMC_SLNO, MAX(IRD_DATE) AS IRD_DATE
        FROM IPRECEIPT
        GROUP BY DMC_SLNO
    ) LATEST_RECEIPT ON I.DMC_SLNO = LATEST_RECEIPT.DMC_SLNO              
    LEFT JOIN DOCTOR D ON I.DO_CODE = D.DO_CODE
    LEFT JOIN SPECIALITY S ON D.SP_CODE = S.SP_CODE
    LEFT JOIN DEPARTMENT DP ON S.DP_CODE = DP.DP_CODE
    LEFT JOIN BED B ON I.BD_CODE = B.BD_CODE
    LEFT JOIN NURSTATION N ON B.NS_CODE = N.NS_CODE 
      LEFT JOIN ADMNREASON AD ON I.RS_CODE=AD.RS_CODE
    LEFT JOIN (
        SELECT * FROM (
            SELECT IP_NO, APRVD_DATE,
                   ROW_NUMBER() OVER (PARTITION BY IP_NO ORDER BY APRVD_DATE DESC NULLS LAST) AS RN
            FROM CLINICAL.DISCHARGESUMMARY
        ) WHERE RN = 1
    ) DS ON I.IP_NO = DS.IP_NO  
    LEFT JOIN (
        SELECT * FROM (
            SELECT D.*, ROW_NUMBER() OVER(PARTITION BY IP_NO ORDER BY REQ_DATE DESC) RN
            FROM DISREQUESTDETL D
        ) WHERE RN = 1
    ) DD ON I.IP_NO = DD.IP_NO
    LEFT JOIN (
        SELECT * FROM (
            SELECT IP_NO, MRC_SLNO, MRD_DATE,
                   ROW_NUMBER() OVER (PARTITION BY IP_NO ORDER BY MRD_DATE DESC) AS RN
            FROM MRETREQMAST
        ) WHERE RN = 1
    ) LATEST_MRETREQMAST ON I.IP_NO = LATEST_MRETREQMAST.IP_NO
    LEFT JOIN (
        SELECT MRC_SLNO, MAX(MRD_RETDATE) AS MRD_RETDATE
        FROM MRETMAST
        GROUP BY MRC_SLNO
    ) LATEST_MRETMAST ON LATEST_MRETREQMAST.MRC_SLNO = LATEST_MRETMAST.MRC_SLNO
    LEFT JOIN (
        SELECT * FROM (
            SELECT PT.*, ROW_NUMBER() OVER(PARTITION BY IP_NO ORDER BY DRD_DATE DESC) RN
            FROM PATDRGREQMST PT
            WHERE PT.DRC_DISCHARGEADVICE = 'Y'
        ) WHERE RN = 1
    ) LATEST_PATDRGREQMST ON I.IP_NO = LATEST_PATDRGREQMST.IP_NO 
    LEFT JOIN (
        SELECT IP_NO, BMD_DISPENSETIME 
        FROM (
            SELECT PB.IP_NO, 
                   PB.BMD_DISPENSETIME,
                   ROW_NUMBER() OVER(PARTITION BY PB.IP_NO ORDER BY PB.BMD_DISPENSETIME DESC) AS RN
            FROM PBILLMAST PB
            INNER JOIN PATDRGREQMST PM ON PB.BMC_SLNO = PM.BMC_SLNO
            WHERE PB.BMC_DISPENSED = 'Y' 
              AND PM.DRC_DISCHARGEADVICE = 'Y'
        ) WHERE RN = 1
    ) LATEST_PBILLMAST ON I.IP_NO = LATEST_PBILLMAST.IP_NO   
WHERE TRUNC(I.IPD_DISC) BETWEEN to_date(:FROM_DATE,'dd/MM/yyyy hh24:mi:ss') AND to_date(:TO_DATE,'dd/MM/yyyy hh24:mi:ss')
  AND I.IPC_PTFLAG = 'N'
ORDER BY I.DMD_DATE
  `;

    try {
      const result = await executeTmc(
        sql,
        {
          FROM_DATE: FROM_DATE,
          TO_DATE: TO_DATE,
        },
        { outFormat: oracledb.OUT_FORMAT_OBJECT },
      );

      const seen = new Set();
      const uniqueRows = [];
      (result.rows || []).forEach((row, idx) => {
        const key = row.ADMISS_NO || row.PATIENT_NO + '_' + row.ADMIS_DATE_TIME;
        if (key) {
          if (!seen.has(key)) {
            seen.add(key);
            uniqueRows.push({ ...row, SLNO: uniqueRows.length + 1 });
          }
        } else {
          uniqueRows.push({ ...row, SLNO: uniqueRows.length + 1 });
        }
      });

      return uniqueRows;
    } catch (error) {
      console.log(error);
      throw error;
    }
  },

};
